---
sql_root: 
maria_db_packages: 
  - MariaDB-server
  - MariaDB-client
install_packages_php:
  - httpd
  - php #this might have to be php73 for centos
  - php-common #this is just needed for amazon linux 
  - php-devel
  - php-gd
  - php-imap
  - php-ldap
  - php-mysql
  - php-odbc
  - php-pear
  - php-xml
  - php-xmlrpc
  - php-mbstring
  - php-mcrypt
  - php-mhash
  - gettext
install_packages_pdns:
  - epel-release
  - pdns
  - pdns-backend-mysql
  - yum-utils
install_packages_pear:
  - php-pear-DB
  - php-pear-MDB2-Driver-mysqli


