---
- name: adding mariadb repo
  ansible.builtin.copy:
    src: files/mariadb.repo
    dest: /etc/yum.repos.d/mariadb.repo

- name: running makecache
  ansible.builtin.command: yum makecache --disablerepo='*' --enablerepo='mariadb'

- name: installing mariaDB packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "MariaDB-server"
    - "MariaDB-client"
  notify: Start MariaDB

- name: start mariadb ##remove later
  ansible.builtin.service:
    name: mariadb
    state: started
   
- name: flush handlers
  meta: flush_handlers

- name: change mariadb password
  ansible.builtin.command: mysql -uroot --execute="set password = password('{{ sql_root }}');"

- name: stop mariaDB
  ansible.builtin.service:
    name: mariadb
    state: started

- name: SELinux set to permissive
  ansible.builtin.command: sed -i s/^SELINUX=.*$/SELINUX=disabled/ /etc/selinux/config
  register: need_reboot

- name: reboot and wait to come back 
  reboot:
    reboot_timeout: 3600
  when: need_reboot.changed

- name: copy server.cnf file over
  ansible.builtin.copy:
    src: files/server.cnf
    dest: /etc/my.cnf.d/server.cnf

- name: stop mariadb
  ansible.builtin.service:
    name: mariadb
    state: stopped
