---
- name: adding mariadb repo
  ansible.builtin.copy:
    src: files/mariadb.repo
    dest: /etc/yum.repos.d/mariadb.repo

- name: running makecache
  ansible.builtin.command: yum makecache --disablerepo='*' --enablerepo='mariadb'

- name: installing mariaDB packages
  yum:
    name: "{{ maria_db_packages }}"
    state: present
  notify: Start MariaDB
   
- name: flush handlers
  meta: flush_handlers

- name: change mariadb password
  ansible.builtin.command: mysql -uroot --execute="set password = password('{{ sql_root }}');"

- name: stop mariaDB
  ansible.builtin.service:
    name: mariadb
    state: started

- name: SELinux set to permissive
  ansible.builtin.command: sed -i s/^SELINUX=.*$/SELINUX=disabled/ /etc/selinux/config
  register: need_reboot

- name: reboot and wait to come back 
  reboot:
    reboot_timeout: 3600
  when: need_reboot.changed

- name: copy server.cnf file over
  ansible.builtin.copy:
    src: files/server.cnf
    dest: /etc/my.cnf.d/server.cnf
  notify: Stop MariaDB

- name: flush handlers
  meta: flush_handlers

- name: installing php packages
  yum:
    name: "{{ install_packages_php }}"
    state: present

- name: enabling php 7 
  ansible.builtin.command: yum-config-manager --enable remi-php7

- name: install pdns
  yum: 
    name: "{{ install_packages_pdns }}"
    state: present

- name: install pear packages
  yum: 
    name: "{{ install_packages_pear }}"
    state: present

- name: remove current pdns launch type 
  lineinfile: 
    path: /etc/pdns/pdns.conf
    regexp: '^%launch=bind'
    state: absent
  register: pdns_config

- name: configure pdns file 
  blockinfile:
    path: /etc/pdns/pdns.conf
    marker: "##ansible managed configuration"
    insertafter: "launch which backends"
    block: | 
      launch=gmysql
      gmysql-host=localhost
      gmysql-user=power_admin
      gmysql-password={{ sql_root }}
      gmysql-dbname=powerdns
  when: pdns_config.changed

- name: enabling services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "httpd"
    - "pdns"





